### ISSUE TITLE
Documentation on how to setup with traefik

### ISSUE THREAD

**Issue by 13hannes11** [SelfhostedPro/Yacht-Docs#2]
I would like to run yacht behind traefika s reverse prox, however something seems to be missing in my config and I cannot figure out what, based on the documentation.

```yml
version: "3.3"
services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    environment:
      - COMPOSE_DIR=/compose/
    volumes:
      - yacht_data:/config
      - ../:/compose
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.yacht.entrypoints=http"
      - "traefik.http.routers.yacht.rule=Host(`yacht.domain.com`)"
      - "traefik.http.middlewares.yacht-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.yacht.middlewares=yacht-https-redirect"
      - "traefik.http.routers.yacht-secure.entrypoints=https"
      - "traefik.http.routers.yacht-secure.rule=Host(`yacht.domain.com`)"
      - "traefik.http.routers.yacht-secure.tls=true"
      - "traefik.http.routers.yacht-secure.tls.certresolver=http"
      - "traefik.http.routers.yacht-secure.service=yacht"
      - "traefik.http.services.yacht.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    restart: always
volumes:
  yacht_data:
networks:
  proxy:
    external: true

```

**Comment by SelfhostedPro** [comment]
Here's a traefik setup that has worked for me in the past: https://github.com/SelfhostedPro/Redcloud/blob/master/docker-compose.yml

**Comment by 13hannes11** [comment]
Sadly this config only works for traefik 1.x not for 2.x and I am having trouble figuring out what settings I need to change.

When I expose port 8000 directly I can reach it but not if I try via traefik.

**Comment by ZachMyers3** [comment]
Here is my ```docker-compose.yml``` that I was able to use yacht behind traefik with.

```yaml
---
version: "3"

networks:
  traefik_network:
    external:
      name: web

services:
  yacht:
    image: selfhostedpro/yacht:devel
    restart: unless-stopped
    networks:
      - traefik_network
    environment:
      - PUID=1000
      - PGID=1000
      - "SECRET_KEY=my_secret_key"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./config:/config
    labels:
      - "traefik.http.services.yacht.loadbalancer.server.scheme=http"
      - "traefik.http.services.yacht.loadbalancer.server.port=8000"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.yacht-http.service=yacht"
      - "traefik.http.routers.yacht-http.rule=Host(`yacht.domain.tld`)"
      - "traefik.http.routers.yacht-http.entrypoints=http"
      - "traefik.http.routers.yacht.service=yacht"
      - "traefik.http.routers.yacht.rule=Host(`yacht.domain.tld`)"
      - "traefik.http.routers.yacht.entrypoints=https"
      - "traefik.http.routers.yacht.tls=true"
      - "traefik.http.routers.yacht.tls.certresolver=dns"
      - "traefik.http.routers.yacht.tls.domains[0].main=domain.tld"
      - "traefik.http.routers.yacht.tls.domains[0].sans=*.domain.tld"
```
